### ISSUE TITLE
Update NPM package to latest

### ISSUE THREAD

**Issue by andreafdaf** [lammertw/prerender-mongodb-cache#12]
I've noticed that v0.0.2 which comes as latest from NPM still uses driver version ~1.3.23 so it doesn't work with MongoDB instances running v3.x because of the new auth mechanism

There is already a commit with the latest MongoDB driver in package.json 91ffe9fb0f30a8f094d00f7a60a60fd5b0a1dd5d

If you could please upload this new version to NPM it would be great! Thanks :v:

**Comment by 4garfield** [comment]
same issue here, please update

**Comment by jainisenough** [comment]
Try the updated version yourself, its working fine:

    "mongodb": "^2.2.24",
    "cache-manager": "^2.4.0"
